name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Create Draft Release
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -c release
    - name: Zip
      run: zip -j live-edge-query.zip .build/release/live-edge-query
    - name: Create Date Tag
      id: create_date_tag
      run: echo "::set-output name=date_tag::$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_date_tag.outputs.date_tag }}
        release_name: "Draft ${{ steps.create_date_tag.outputs.date_tag }}"
        draft: true
        prerelease: false
    - name: Upload Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: swift-timer.zip
        asset_name: swift-timer.zip
        asset_content_type: application/zip
